### ISSUE TITLE
Open Links in New Tab

### ISSUE THREAD

**Issue by varnum** [mlibrary/mgetit#45]
Feedback from Karen Reiman-Sendi (in email, Sun, Sep 18, 2016 at 2:30 PM):

> I just noticed that when I click on the "go to xxxx" link to actually connect to the full text of 
> something I found, it doesn't launch a new browser tab. I think that might not be ideal. 
> If we keep the M Get It page in front of them, one could easily report a linking problem (or in a case 
> from yesterday, report that there is a missing page in article, from all our subscription sources). 

Does it make sense to open MGet It links from Umlaut to the item in a new window?

**Comment by jonearley** [comment]
This is a common suggestion from advanced users, but the user studies on it say not to open in a new tab. It's creates unpredictable behavior. Opening something in a new tab should be left to the user to handle in their browser.

Even in the two user tests I participated in with @bnhowell one user tried to use the back button and it didn't do what the user expected because that tab opened in a new window. The user didn't notice the new tab opened and so thought the back button was broken.

It's in the best interest to not open in a new tab.

**Comment by jonearley** [comment]
The suggestion I would make to Karen is if she wants links opened in a new tab, she should use her browser to open links in a new tab.

**Comment by varnum** [comment]
How about for error correction, when the selected full-text link doesn't work? The user then has lost the other option(s), as well as ways to get help, without starting over at the original citation.

**Comment by jonearley** [comment]
The user is not lost. They are in control of their browser by making the page open in the same window. If the user wants to do error correction, or get back to the page they can either 1) use the back button if they opened in the same window or 2) open the link in a new tab under their control (ex: right click and open in new tab).

**Comment by jonearley** [comment]
http://libux.co/links-should-open-in-the-same-window/

**Comment by jonearley** [comment]
>  links that don’t behave as expected undermine users’ understanding of their own system

source: https://www.nngroup.com/articles/top-10-mistakes-web-design/

**Comment by jonearley** [comment]
I'm going to close this issue as it's been a talked about UX thing for a while and the expert answer is: **leave the default link behavior alone**.

**Comment by bnhowell** [comment]
I agree with @jonearley 
User behavior has overwhelmingly been to navigate back and forward using the browser or they open a new tab themselves for multiple options.

**Comment by varnum** [comment]
I disagree with this decision because one of the main points of the MGet It
interface is to *provide assistance when the link doesn't work*. Many
full-text links involve multiple hops, including through CoSign
authentication and through multiple hops on the vendor's site, wherein the
back button will not always go back to the previous screen. Forcing the
user to restart the document request from the source feels
counterproductive.




--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
http://www.lib.umich.edu/users/varnum

**Comment by jonearley** [comment]
@varnum This decision doesn't make anyone restart or make our efforts counterproductive. I promise. If we prevent a link from functioning in it's default behavior it undermines the users' understanding of their own system.

It's bad UX to force a new tab. It's been studied and Ben and I have seen the open in new tab completely fail in testing. Our user thought the back button was broken because we took over what the they thought a link did. Forcing a new tab broke that promise on a predictable link.

The user Ben tested we failed the *provide assistance when the link doesn't work* because we in all essence broke the link for the user. She couldn't get back and had to start over.

**Comment by varnum** [comment]
I guess this is one of those cases where my typical behavior is atypical of most users. 

Keep it as it is, and we'll see what, if any, feedback we get

**Comment by varnum** [comment]
(And by "keep it as it is", I mean with the behavior currently in place: links open in the same tab, not a new tab.)

**Comment by jonearley** [comment]
I accidentally hit reopen -- whoops. If an argument can be made with user testing to back it I'd consider opening in a new tab. :)

**Comment by varnum** [comment]
Re-closing....
